apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - image: kilburn.jb.man.ac.uk/orppst/keycloak:latest
        args: ["start", "--import-realm", "--log-level=DEBUG", "--hostname-debug=true"]
        name: keycloak
        env:
        - name: KC_DB_VENDOR
          value: "postgres"
        - name: KC_DB_ADDR
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: host } }
        - name: KC_DB_PORT
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: port } }
        - name: KC_DB_DATABASE
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: dbname } }
        - name: KC_DB_USER
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: user } }
        - name: KC_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: password } }
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloakadm-secret
              key: username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
             secretKeyRef:
                name: keycloakadm-secret
                key: username
# TODO make the proxying more secure, by only exposing what is necessary -https://www.keycloak.org/server/hostname https://www.keycloak.org/server/reverseproxy https://www.keycloak.org/server/all-config
        - name: KC_PROXY
          value: "edge"
        - name: KC_HOSTNAME
          value: "kilburn.jb.man.ac.uk"
        - name: KC_HTTP_RELATIVE_PATH
          value: "/aai/"
        - name: KC_HOSTNAME_STRICT_BACKCHANNEL
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /aai/realms/master
            port: 8080
      restartPolicy: Always
