apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pst-document-store
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
